baseURL = "https://greencoastorganics.netlify.app/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 10
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3